### ISSUE TITLE
Support cargo-dinghy as a cargo test runner

### ISSUE THREAD

**Issue by briansmith** [sonos/dinghy#210]
Now, cargo-dinghy controls the build and basically the entire cargo invocation, as the `cargo dinghy` command replaces (wraps) the command the user is trying to run. It would be nice to support an alternative mode where we continue to use `cargo test`, etc., but where cargo-dinghy is invoked by cargo as needed as a test runner.

In https://github.com/sonos/dinghy/pull/203, @simlay a way of approximating this with the current feature set, with their cargo.config that looked like this:

```toml
[target.aarch64-apple-watchos-sim]
runner = "cargo run --manifest-path ../../Cargo.toml --bin cargo-dinghy -- -p auto-watchos-aarch64-sim runner"

[target.x86_64-apple-watchos-sim]
runner = "cargo run --manifest-path ../../Cargo.toml --bin cargo-dinghy -- -p auto-watchos-x86_64-sim runner"

[target.aarch64-apple-tvos-sim]
runner = "cargo run --manifest-path ../../Cargo.toml --bin cargo-dinghy -- -p auto-tvos-aarch64-sim runner"

[target.x86_64-apple-tvos]
runner = "cargo run --manifest-path ../../Cargo.toml --bin cargo-dinghy -- -p auto-tvos-x86_64 runner"

[target.aarch64-apple-ios-sim]
runner = "cargo run --manifest-path ../../Cargo.toml --bin cargo-dinghy -- -p auto-ios-aarch64-sim runner"

[target.x86_64-apple-ios]
runner = "cargo run --manifest-path ../../Cargo.toml --bin cargo-dinghy -- -p auto-ios-x86_64 runner"
```

Imagine that we had an argument `cargo-runner` so that when invoked like `cargo-dinghy cargo-runner`, cargo-dinghy would use the environment variables set by Cargo to detect what the `--target` passed to `cargo test` was. Then it would use the cargo target to derive the`-p` argument automatically. Then the above config.toml could be reduced reduce to something like (for most projects):
```
[target.'cfg(all(any(target_arch="aarch64",target_arch="x86_64"),target_vendor="apple",any(target_os="ios",target_os="tvos",target_os="-apple-watchos")))']
runner = "cargo-dinghy cargo-runner"
```

For more complex projects, such a mode would may need a configuration mechanism (file) that would take over the duty of the command line arguments.
